security:
    # https://symfony.com/doc/current/security.html#registering-the-user-hashing-passwords
    password_hashers:
        Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface: 'auto'

    # https://symfony.com/doc/current/security.html#loading-the-user-the-user-provider
    providers:
        app_user_provider:
            entity:
                class: App\Entity\User
                property: email

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            pattern: ^/(?!login$).*
            # Authentification par formulaire
            form_login:
                login_path: login
                check_path: login
                default_target_path: home
                username_parameter: email
                password_parameter: password

            # Si l'utilisateur est déconnecté, il sera redirigé vers la page de login
            logout:
                path: /logout
                target: /login

    # Contrôles d'accès pour protéger les pages
    access_control:
        # Page de login accessible sans authentification
        - { path: ^/login$, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        # Pages principales accessibles uniquement aux utilisateurs authentifiés
        - { path: ^/admin, roles: ROLE_ADMIN }
        - { path: ^/profile, roles: ROLE_USER }

    # Lazy loading, par défaut c'est true, cela ne doit pas être utilisé directement sous "firewalls"
    # lazy: false
    # provider: app_user_provider
